
services:
  web:
    build:
      context: .
      dockerfile: mnist_classifier/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mnist
      - DB_USER=postgres
      - DB_PASSWORD=example
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mnist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata: